package io.example;

import com.microsoft.playwright.Locator;
import com.microsoft.playwright.Page;
import com.microsoft.playwright.options.AriaRole;

/** Generated by Frap — do not edit by hand. */
public class DuckDuckGoSearchPage {
    private final Page page;

    public DuckDuckGoSearchPage(Page page) {
        this.page = page;
    }

    /** Cluster `cluster_div__nohref__L_L_L_L_L_L_L_L_L` (2 elements) */
    public Locator divItems(int index) {
        return page.locator("[data-testid=\"home-minimal\"]").nth(index);
    }

    /** Cluster `cluster_a__href__L_L` (3 elements) */
    public Locator aItems(int index) {
        return page.locator("[data-testid=\"aichat-button\"]").nth(index);
    }

    /** Cluster `cluster_button__nohref__L` (3 elements) */
    public Locator buttonItems(int index) {
        return page.locator("[data-testid=\"sidemenu-button\"]").nth(index);
    }

    /** Cluster `cluster_input__nohref__notext` (8 elements) */
    public Locator inputItems(int index) {
        return page.locator("div[data-testid=\"ai-toggle\"] > label:nth-of-type(1) > input").nth(index);
    }

    /** Cluster `cluster_button__nohref__notext` (4 elements) */
    public Locator buttonItems2(int index) {
        return page.locator("div[data-testid=\"ai-toggle\"] > label:nth-of-type(1) > span > button").nth(index);
    }

    /** Cluster `cluster_a__href_mac__L` (3 elements) */
    public Locator aItems2(int index) {
        return page.locator("div:nth-of-type(1) > ul > ul:nth-of-type(1) > li:nth-of-type(1) > a").nth(index);
    }

    /** Cluster `cluster_a__href_windows__L` (3 elements) */
    public Locator aItems3(int index) {
        return page.locator("div:nth-of-type(1) > ul > ul:nth-of-type(1) > li:nth-of-type(2) > a").nth(index);
    }

    /** Cluster `cluster_a__href_app_duckduckgo_privacy_browser____L` (3 elements) */
    public Locator aItems4(int index) {
        return page.locator("div:nth-of-type(1) > ul > ul:nth-of-type(2) > li:nth-of-type(1) > a").nth(index);
    }

    /** Cluster `cluster_a__href_store_apps_details__L` (3 elements) */
    public Locator aItems5(int index) {
        return page.locator("div:nth-of-type(1) > ul > ul:nth-of-type(2) > li:nth-of-type(2) > a").nth(index);
    }

    /** Cluster `cluster_a__href_________duckduckgo_browser_windows_download__L_L_L_L_L_L_L_L_L_L_L_L_L_L_L_L_L_L_L` (2 elements) */
    public Locator aItems6(int index) {
        return page.locator("section:nth-of-type(2) > div > div > div:nth-of-type(1) > a").nth(index);
    }

    /** Cluster `cluster_a__href_story_privacy_browsers_duckduckgo_ghostery_brave__L_L_L_L_L_L_L_L_L_L` (2 elements) */
    public Locator aItems7(int index) {
        return page.locator("section:nth-of-type(2) > div > div > div:nth-of-type(2) > a").nth(index);
    }

    /** Cluster `cluster_a__href____L_L_L_L_L_L_L_L_L_L_L_L_L_L_L` (2 elements) */
    public Locator aItems8(int index) {
        return page.locator("section:nth-of-type(2) > div > div > div:nth-of-type(3) > a").nth(index);
    }

    /** Cluster `cluster_a__href_tech_services_and_software_five_reasons_you_should_use_duckduckgo_instead_of_google__L_L_L_L_L_L_L_L_L_L` (2 elements) */
    public Locator aItems9(int index) {
        return page.locator("section:nth-of-type(2) > div > div > div:nth-of-type(4) > a").nth(index);
    }

    /** Cluster `cluster_a__href_pro_duckduckgo_private_browser__L_L_L_L_L_L` (2 elements) */
    public Locator aItems10(int index) {
        return page.locator("section:nth-of-type(2) > div > div > div:nth-of-type(5) > a").nth(index);
    }

    /** Cluster `cluster_a__href_us_app_duckduckgo_private_browser____L_L_L_L_L_L_L_L_L_L_L_L_L_L_L` (2 elements) */
    public Locator aItems11(int index) {
        return page.locator("section:nth-of-type(2) > div > div > div:nth-of-type(6) > a").nth(index);
    }

    /** Cluster `cluster_a__href_us_app_duckduckgo_private_browser____L_L_L_L_L_L_L_L_L_L_L_L_L_L` (2 elements) */
    public Locator aItems12(int index) {
        return page.locator("section:nth-of-type(2) > div > div > div:nth-of-type(7) > a").nth(index);
    }

    /** Cluster `cluster_a__href_us_app_duckduckgo_private_browser____L_L_L_L_L_L_L_L_L_L_L_L_L_L_L_L_L_L` (2 elements) */
    public Locator aItems13(int index) {
        return page.locator("section:nth-of-type(2) > div > div > div:nth-of-type(8) > a").nth(index);
    }

    /** Cluster `cluster_a__href_store_apps_details__L_L_L_L_L_L_L_L_L_L_L_L_L` (4 elements) */
    public Locator aItems14(int index) {
        return page.locator("section:nth-of-type(2) > div > div > div:nth-of-type(9) > a").nth(index);
    }

    /** Cluster `cluster_a__href_store_apps_details__L_L_L_L_L_L_L_L_L_L_L_L_L_L_L_L` (2 elements) */
    public Locator aItems15(int index) {
        return page.locator("section:nth-of-type(2) > div > div > div:nth-of-type(10) > a").nth(index);
    }

    /** Cluster `cluster_a__href_compare_privacy__L_L_L_L_L_L_L` (2 elements) */
    public Locator aItems16(int index) {
        return page.locator("div#react-aria3367922960-_r_56_ > div > p > a:nth-of-type(1)").nth(index);
    }

    /** Cluster `cluster_a__href_duckduckgo_help_pages_company_how_duckduckgo_makes_money__L_L_L_L` (3 elements) */
    public Locator aItems17(int index) {
        return page.locator("div#react-aria3367922960-_r_56_ > div > p > a:nth-of-type(3)").nth(index);
    }

    /** Cluster `cluster_a__href_duckduckgo_help_pages_privacy_pro__L_L` (2 elements) */
    public Locator aItems18(int index) {
        return page.locator("div#react-aria3367922960-_r_5b_ > div > div > p:nth-of-type(2) > a:nth-of-type(6)").nth(index);
    }

    /** Cluster `cluster_a__href_duckduckgo_help_pages_company_how_does_duckduckgo_protect_privacy__L_L` (3 elements) */
    public Locator aItems19(int index) {
        return page.locator("div#react-aria3367922960-_r_5b_ > div > div > p:nth-of-type(2) > a:nth-of-type(11)").nth(index);
    }

    /** Cluster `cluster_a__href_duckduckgo_help_pages_privacy_web_tracking_protections__L_L_L` (6 elements) */
    public Locator aItems20(int index) {
        return page.locator("div#react-aria3367922960-_r_5g_ > div > div > p:nth-of-type(1) > a:nth-of-type(2)").nth(index);
    }

    /** div (confidence 0.98) */
    // signature prefix: div:->div:-
    public Locator duckAiMainNavigationMenu() {
        return page.getByTestId("home-minimal");
    }

    /** div (confidence 0.98) */
    // signature prefix: div:->div:->main:->div:-
    public Locator duckAiMainNavigationMenu2() {
        return page.getByTestId("home-hero");
    }

    /** a (confidence 0.98) */
    // signature prefix: div:->div:->main:->div:->div:-
    public Locator duckAiLink() {
        return page.getByTestId("aichat-button");
    }

    /** button (confidence 0.98) */
    // signature prefix: div:->div:->main:->div:->div:-
    public Locator menuButton() {
        return page.getByTestId("sidemenu-button");
    }

    /** div (confidence 0.98) */
    // signature prefix: div:->div:->main:->div:->div:-
    public Locator searchDuckAi() {
        return page.getByTestId("ai-toggle");
    }

    /** input (confidence 0.90) */
    // signature prefix: div:->div:->main:->div:->div:-
    public Locator inputroleEl5() {
        return page.getByRole(AriaRole.RADIO, new Page.GetByRoleOptions().setName("Search"));
    }

    /** button (confidence 0.90) */
    // signature prefix: div:->div:->main:->div:->div:-
    public Locator searchButton() {
        return page.locator("main").getByLabel("Search");
    }

    /** input (confidence 0.90) */
    // signature prefix: div:->div:->main:->div:->div:-
    public Locator inputroleEl7() {
        return page.getByRole(AriaRole.RADIO, new Page.GetByRoleOptions().setName("Duck.ai"));
    }

    /** button (confidence 0.90) */
    // signature prefix: div:->div:->main:->div:->div:-
    public Locator duckAiButton() {
        return page.getByLabel("Duck.ai");
    }

    /** form (confidence 0.98) */
    // signature prefix: div:->div:->main:->div:->div:-
    public Locator searchTheWebWith() {
        return page.getByTestId("searchbox-form");
    }

    /** input (confidence 0.40) */
    // signature prefix: div:->div:->main:->div:->div:-
    public Locator inputcssEl10() {
        return page.locator("form#searchbox_homepage > input:nth-of-type(1)");
    }

    /** input (confidence 0.40) */
    // signature prefix: div:->div:->main:->div:->div:-
    public Locator inputcssEl11() {
        return page.locator("form#searchbox_homepage > input:nth-of-type(2)");
    }

    /** input (confidence 0.40) */
    // signature prefix: div:->div:->main:->div:->div:-
    public Locator inputcssEl12() {
        return page.locator("form#searchbox_homepage > input:nth-of-type(3)");
    }

    /** input (confidence 0.40) */
    // signature prefix: div:->div:->main:->div:->div:-
    public Locator inputcssEl13() {
        return page.locator("form#searchbox_homepage > input:nth-of-type(4)");
    }

    /** input (confidence 0.40) */
    // signature prefix: div:->div:->main:->div:->div:-
    public Locator inputcssEl14() {
        return page.locator("form#searchbox_homepage > input:nth-of-type(5)");
    }

    /** input (confidence 0.40) */
    // signature prefix: div:->div:->main:->div:->div:-
    public Locator inputcssEl15() {
        return page.locator("form#searchbox_homepage > input:nth-of-type(6)");
    }

    /** input (confidence 0.90) */
    // signature prefix: div:->div:->main:->div:->div:-
    public Locator searchWithDuckDuckGoInput() {
        return page.getByLabel("Search with DuckDuckGo");
    }

    /** button (confidence 0.90) */
    // signature prefix: div:->div:->main:->div:->div:-
    public Locator searchButton2() {
        return page.locator("form#searchbox_homepage[aria-label=\"Search the web with DuckDuckGo\"]").getByLabel("Search");
    }

    /** a (confidence 0.90) */
    // signature prefix: div:->div:->main:->div:->div:-
    public Locator protectionPrivacyPeaceOfLink() {
        return page.getByRole(AriaRole.LINK, new Page.GetByRoleOptions().setName("Protection. Privacy. Peace of mind."));
    }

    /** button (confidence 0.98) */
    // signature prefix: div:->div:->main:->div:->div:-
    public Locator aISettingsButton() {
        return page.getByTestId("home-customize-trigger");
    }

    /** div (confidence 0.98) */
    // signature prefix: div:->div:->main:->div:->div:-
    public Locator divtestidEl20() {
        return page.getByTestId("pull-tab-scroll-button");
    }

    /** button (confidence 0.90) */
    // signature prefix: div:->div:->main:->div:->div:-
    public Locator scrollDownToLearnButton() {
        return page.getByLabel("Scroll down to learn more");
    }

    /** div (confidence 0.75) */
    // signature prefix: div:->div:->main:->div:-
    public Locator protectYourPersonalInformation() {
        return page.locator("#features");
    }

    /** div (confidence 0.98) */
    // signature prefix: div:->div:->main:->div:->div:-
    public Locator desktopMobileBrowserDuckDuckGoBrowserMacWindowsiOSAndroidDesktop() {
        return page.getByTestId("download-options");
    }

    /** a (confidence 0.37) */
    // signature prefix: div:->div:->main:->div:->div:-
    /** matches 3 — уточните */
    public Locator macLink() {
        return page.locator("[href=\"https://duckduckgo.com/mac?origin=funnel_home_website__details\"]").first();
    }

    /** a (confidence 0.37) */
    // signature prefix: div:->div:->main:->div:->div:-
    /** matches 3 — уточните */
    public Locator windowsLink() {
        return page.locator("[href=\"https://duckduckgo.com/windows?origin=funnel_home_website__details\"]").first();
    }

    /** a (confidence 0.55) */
    // signature prefix: div:->div:->main:->div:->div:-
    /** matches 2 — уточните */
    public Locator iOSLink() {
        return page.locator("[href=\"https://apps.apple.com/app/duckduckgo-privacy-browser/id663592361?platform=iphone&pt=866401&mt=8\"]").first();
    }

    /** a (confidence 0.37) */
    // signature prefix: div:->div:->main:->div:->div:-
    /** matches 9 — уточните */
    public Locator androidLink() {
        return page.locator("[href=\"https://play.google.com/store/apps/details?id=com.duckduckgo.mobile.android&referrer=origin%3Dfunnel_home_website__details\"]").first();
    }

    /** a (confidence 0.92) */
    // signature prefix: div:->div:->main:->div:->div:-
    public Locator chromeLink() {
        return page.locator("[href=\"https://chrome.google.com/webstore/detail/duckduckgo-privacy-essent/bkdgflcldnnnapblkhphbgpggdiikppg\"]");
    }

    /** a (confidence 0.92) */
    // signature prefix: div:->div:->main:->div:->div:-
    public Locator edgeLink() {
        return page.locator("[href=\"https://microsoftedge.microsoft.com/addons/detail/caoacbimdbbljakfhgikoodekdnlcgpk\"]");
    }

    /** a (confidence 0.92) */
    // signature prefix: div:->div:->main:->div:->div:-
    public Locator firefoxLink() {
        return page.locator("[href=\"https://addons.mozilla.org/en-US/firefox/addon/duckduckgo-for-firefox/\"]");
    }

    /** a (confidence 0.92) */
    // signature prefix: div:->div:->main:->div:->div:-
    public Locator operaLink() {
        return page.locator("[href=\"https://addons.opera.com/en/extensions/details/duckduckgo-for-opera-2/\"]");
    }

    /** button (confidence 0.90) */
    // signature prefix: div:->div:->main:->div:->div:-
    public Locator privateSearchButton() {
        return page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Private Search"));
    }

    /** button (confidence 0.54) */
    // signature prefix: div:->div:->main:->div:->div:-
    /** matches 2 — уточните */
    public Locator duckAiButton2() {
        return page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Duck.ai")).first();
    }

    /** button (confidence 0.90) */
    // signature prefix: div:->div:->main:->div:->div:-
    public Locator subscriptionButton() {
        return page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Subscription"));
    }

    /** button (confidence 0.90) */
    // signature prefix: div:->div:->main:->div:->div:-
    public Locator emailButton() {
        return page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Email"));
    }

    /** main (confidence 0.98) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator searchOrEnterAddressSearch() {
        return page.getByTestId("homepage-btf");
    }

    /** section (confidence 0.98) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator searchOrEnterAddressSearch2() {
        return page.getByTestId("app-hero");
    }

    /** button (confidence 0.90) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator evadeScamsDataHungryButton() {
        return page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Evade scams & data-hungry companiesProtection"));
    }

    /** button (confidence 0.90) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator blockMostAdsCookieButton() {
        return page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Block most ads & cookie pop-upsPrivacy"));
    }

    /** button (confidence 0.90) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator searchChatWithoutBeingButton() {
        return page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Search & chat without being trackedPeace of Mind"));
    }

    /** div (confidence 0.59) */
    // signature prefix: div:->div:->main:->div:->main:-
    /** matches 2 — уточните */
    public Locator seeHowDuckDuckGoCompares() {
        return page.getByTestId("belowTheFold").first();
    }

    /** a (confidence 0.90) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator compareMoreProtectionsLink() {
        return page.getByRole(AriaRole.LINK, new Page.GetByRoleOptions().setName("Compare More Protections"));
    }

    /** a (confidence 0.37) */
    // signature prefix: div:->div:->main:->div:->main:-
    /** matches 3 — уточните */
    public Locator windowsLink2() {
        return page.locator("[href=\"https://duckduckgo.com/windows?origin=funnel_home_website__details\"]").first();
    }

    /** a (confidence 0.37) */
    // signature prefix: div:->div:->main:->div:->main:-
    /** matches 3 — уточните */
    public Locator macLink2() {
        return page.locator("[href=\"https://duckduckgo.com/mac?origin=funnel_home_website__details\"]").first();
    }

    /** a (confidence 0.37) */
    // signature prefix: div:->div:->main:->div:->main:-
    /** matches 9 — уточните */
    public Locator androidLink2() {
        return page.locator("[href=\"https://play.google.com/store/apps/details?id=com.duckduckgo.mobile.android&referrer=origin%3Dfunnel_home_website__details\"]").first();
    }

    /** a (confidence 0.55) */
    // signature prefix: div:->div:->main:->div:->main:-
    /** matches 2 — уточните */
    public Locator iOSLink2() {
        return page.locator("[href=\"https://apps.apple.com/app/duckduckgo-privacy-browser/id663592361?platform=iphone&pt=866401&mt=8\"]").first();
    }

    /** section (confidence 0.98) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator takeBackControlOf() {
        return page.getByTestId("app-feature-cards");
    }

    /** button (confidence 0.90) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator goodbyeIncognitoModeHelloButton() {
        return page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Goodbye Incognito mode, hello real privacy in every tab"));
    }

    /** button (confidence 0.90) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator block3rdPartyTrackersButton() {
        return page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Block 3rd-party trackers from Google, Facebook, and others"));
    }

    /** button (confidence 0.90) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator deleteAllTabsHistoryButton() {
        return page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Delete all tabs, history, and browsing data in one click"));
    }

    /** button (confidence 0.90) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator stopAdsFollowingYouButton() {
        return page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Stop ads following you everywhere"));
    }

    /** button (confidence 0.90) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator blockAnnoyingCookiePopButton() {
        return page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Block annoying cookie pop-ups"));
    }

    /** button (confidence 0.90) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator blockAdsOnYouTubeButton() {
        return page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Block ads on YouTube"));
    }

    /** button (confidence 0.90) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator searchWithoutBeingTrackedButton() {
        return page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Search without being tracked"));
    }

    /** button (confidence 0.90) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator aSimpleSecurePasswordButton() {
        return page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("A simple, secure password manager"));
    }

    /** button (confidence 0.90) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator chatPrivatelyWithPopularButton() {
        return page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Chat privately with popular AI chatbots (optional)"));
    }

    /** a (confidence 0.55) */
    // signature prefix: div:->div:->main:->div:->main:-
    /** matches 2 — уточните */
    public Locator aSolidCrossPlatformLink() {
        return page.locator("[href=\"https://www.theverge.com/2023/6/22/23769084/duckduckgo-browser-windows-download\"]").first();
    }

    /** a (confidence 0.55) */
    // signature prefix: div:->div:->main:->div:->main:-
    /** matches 2 — уточните */
    public Locator youReGettingMaximumLink() {
        return page.locator("[href=\"https://www.wired.com/story/privacy-browsers-duckduckgo-ghostery-brave/\"]").first();
    }

    /** a (confidence 0.55) */
    // signature prefix: div:->div:->main:->div:->main:-
    /** matches 2 — уточните */
    public Locator easyAndQuickToLink() {
        return page.locator("[href=\"https://www.engadget.com/duckduckgo-mac-browser-open-beta-092105957.html\"]").first();
    }

    /** a (confidence 0.55) */
    // signature prefix: div:->div:->main:->div:->main:-
    /** matches 2 — уточните */
    public Locator freesUpBandwidthAndLink() {
        return page.locator("[href=\"https://www.cnet.com/tech/services-and-software/five-reasons-you-should-use-duckduckgo-instead-of-google/\"]").first();
    }

    /** a (confidence 0.55) */
    // signature prefix: div:->div:->main:->div:->main:-
    /** matches 2 — уточните */
    public Locator duckDuckGoIsAMustLink() {
        return page.locator("[href=\"https://www.techradar.com/pro/duckduckgo-private-browser\"]").first();
    }

    /** a (confidence 0.37) */
    // signature prefix: div:->div:->main:->div:->main:-
    /** matches 6 — уточните */
    public Locator theMostIntuitiveWellLink() {
        return page.locator("[href=\"https://apps.apple.com/us/app/duckduckgo-private-browser/id663592361?see-all=reviews\"]").first();
    }

    /** a (confidence 0.37) */
    // signature prefix: div:->div:->main:->div:->main:-
    /** matches 6 — уточните */
    public Locator absolutelyLoveThisBrowserLink() {
        return page.locator("[href=\"https://apps.apple.com/us/app/duckduckgo-private-browser/id663592361?see-all=reviews\"]").first();
    }

    /** a (confidence 0.37) */
    // signature prefix: div:->div:->main:->div:->main:-
    /** matches 6 — уточните */
    public Locator iFindItFasterLink() {
        return page.locator("[href=\"https://apps.apple.com/us/app/duckduckgo-private-browser/id663592361?see-all=reviews\"]").first();
    }

    /** a (confidence 0.37) */
    // signature prefix: div:->div:->main:->div:->main:-
    /** matches 9 — уточните */
    public Locator givesMeJustTheLink() {
        return page.locator("[href=\"https://play.google.com/store/apps/details?id=com.duckduckgo.mobile.android&referrer=origin%3Dfunnel_home_website__details\"]").first();
    }

    /** a (confidence 0.37) */
    // signature prefix: div:->div:->main:->div:->main:-
    /** matches 9 — уточните */
    public Locator itKeepsMyPersonalLink() {
        return page.locator("[href=\"https://play.google.com/store/apps/details?id=com.duckduckgo.mobile.android&referrer=origin%3Dfunnel_home_website__details\"]").first();
    }

    /** a (confidence 0.37) */
    // signature prefix: div:->div:->main:->div:->main:-
    /** matches 9 — уточните */
    public Locator prettyMuchAllYouLink() {
        return page.locator("[href=\"https://play.google.com/store/apps/details?id=com.duckduckgo.mobile.android&referrer=origin%3Dfunnel_home_website__details\"]").first();
    }

    /** a (confidence 0.55) */
    // signature prefix: div:->div:->main:->div:->main:-
    /** matches 2 — уточните */
    public Locator aSolidCrossPlatformLink2() {
        return page.locator("[href=\"https://www.theverge.com/2023/6/22/23769084/duckduckgo-browser-windows-download\"]").first();
    }

    /** a (confidence 0.55) */
    // signature prefix: div:->div:->main:->div:->main:-
    /** matches 2 — уточните */
    public Locator youReGettingMaximumLink2() {
        return page.locator("[href=\"https://www.wired.com/story/privacy-browsers-duckduckgo-ghostery-brave/\"]").first();
    }

    /** a (confidence 0.55) */
    // signature prefix: div:->div:->main:->div:->main:-
    /** matches 2 — уточните */
    public Locator easyAndQuickToLink2() {
        return page.locator("[href=\"https://www.engadget.com/duckduckgo-mac-browser-open-beta-092105957.html\"]").first();
    }

    /** a (confidence 0.55) */
    // signature prefix: div:->div:->main:->div:->main:-
    /** matches 2 — уточните */
    public Locator freesUpBandwidthAndLink2() {
        return page.locator("[href=\"https://www.cnet.com/tech/services-and-software/five-reasons-you-should-use-duckduckgo-instead-of-google/\"]").first();
    }

    /** a (confidence 0.55) */
    // signature prefix: div:->div:->main:->div:->main:-
    /** matches 2 — уточните */
    public Locator duckDuckGoIsAMustLink2() {
        return page.locator("[href=\"https://www.techradar.com/pro/duckduckgo-private-browser\"]").first();
    }

    /** a (confidence 0.37) */
    // signature prefix: div:->div:->main:->div:->main:-
    /** matches 6 — уточните */
    public Locator theMostIntuitiveWellLink2() {
        return page.locator("[href=\"https://apps.apple.com/us/app/duckduckgo-private-browser/id663592361?see-all=reviews\"]").first();
    }

    /** a (confidence 0.37) */
    // signature prefix: div:->div:->main:->div:->main:-
    /** matches 6 — уточните */
    public Locator absolutelyLoveThisBrowserLink2() {
        return page.locator("[href=\"https://apps.apple.com/us/app/duckduckgo-private-browser/id663592361?see-all=reviews\"]").first();
    }

    /** a (confidence 0.37) */
    // signature prefix: div:->div:->main:->div:->main:-
    /** matches 6 — уточните */
    public Locator iFindItFasterLink2() {
        return page.locator("[href=\"https://apps.apple.com/us/app/duckduckgo-private-browser/id663592361?see-all=reviews\"]").first();
    }

    /** a (confidence 0.37) */
    // signature prefix: div:->div:->main:->div:->main:-
    /** matches 9 — уточните */
    public Locator givesMeJustTheLink2() {
        return page.locator("[href=\"https://play.google.com/store/apps/details?id=com.duckduckgo.mobile.android&referrer=origin%3Dfunnel_home_website__details\"]").first();
    }

    /** a (confidence 0.37) */
    // signature prefix: div:->div:->main:->div:->main:-
    /** matches 9 — уточните */
    public Locator itKeepsMyPersonalLink2() {
        return page.locator("[href=\"https://play.google.com/store/apps/details?id=com.duckduckgo.mobile.android&referrer=origin%3Dfunnel_home_website__details\"]").first();
    }

    /** a (confidence 0.37) */
    // signature prefix: div:->div:->main:->div:->main:-
    /** matches 9 — уточните */
    public Locator prettyMuchAllYouLink2() {
        return page.locator("[href=\"https://play.google.com/store/apps/details?id=com.duckduckgo.mobile.android&referrer=origin%3Dfunnel_home_website__details\"]").first();
    }

    /** section (confidence 0.98) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator trustedByTensOf() {
        return page.getByTestId("download-panel");
    }

    /** a (confidence 0.92) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator downloadDuckDuckGoOnTheLink() {
        return page.locator("[href=\"https://apps.apple.com/app/duckduckgo-privacy-browser/id663592361?platform=iphone&ct=home-atb-home&pt=866401&mt=8\"]");
    }

    /** a (confidence 0.92) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator downloadDuckDuckGoOnGoogleLink() {
        return page.locator("[href=\"https://play.google.com/store/apps/details?id=com.duckduckgo.mobile.android&referrer=utm_campaign%3Dhome-atb-home%26origin%3Dfunnel_home_website__details\"]");
    }

    /** section (confidence 0.98) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator stillHaveQuestionsWhat() {
        return page.getByTestId("faq-section");
    }

    /** button (confidence 0.90) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator whatIsDuckDuckGoButton() {
        return page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("What is DuckDuckGo?"));
    }

    /** a (confidence 0.90) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator chooseDuckDuckGoOverChromeLink() {
        return page.locator("main").getByRole(AriaRole.LINK, new Page.GetByRoleOptions().setName("choose DuckDuckGo over Chrome and other browsers"));
    }

    /** a (confidence 0.55) */
    // signature prefix: div:->div:->main:->div:->main:-
    /** matches 2 — уточните */
    public Locator duckAiLink2() {
        return page.locator("[href=\"https://duck.ai\"]").first();
    }

    /** a (confidence 0.37) */
    // signature prefix: div:->div:->main:->div:->main:-
    /** matches 3 — уточните */
    public Locator privacyRespectingSearchAdsLink() {
        return page.locator("[href=\"https://duckduckgo.com/duckduckgo-help-pages/company/how-duckduckgo-makes-money/\"]").first();
    }

    /** a (confidence 0.92) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator learnMoreLink() {
        return page.locator("[href=\"https://duckduckgo.com/duckduckgo-help-pages/company/\"]");
    }

    /** button (confidence 0.90) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator howDoesDuckDuckGoProtectButton() {
        return page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("How does DuckDuckGo protect my privacy?"));
    }

    /** a (confidence 0.92) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator browsersLink() {
        return page.locator("[href=\"https://duckduckgo.com/duckduckgo-help-pages/get-duckduckgo/does-duckduckgo-make-a-browser/\"]");
    }

    /** a (confidence 0.92) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator extensionsLink() {
        return page.locator("[href=\"https://duckduckgo.com/duckduckgo-help-pages/desktop/adding-duckduckgo-to-your-browser/\"]");
    }

    /** a (confidence 0.90) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator trackerBlockingLink() {
        return page.getByRole(AriaRole.LINK, new Page.GetByRoleOptions().setName("tracker blocking"));
    }

    /** a (confidence 0.92) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator increasedEncryptionLink() {
        return page.locator("[href=\"https://duckduckgo.com/duckduckgo-help-pages/privacy/web-tracking-protections/#smarter-encryption-https-upgrading\"]");
    }

    /** a (confidence 0.92) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator emailProtectionLink() {
        return page.locator("[href=\"https://duckduckgo.com/duckduckgo-help-pages/email-protection/what-is-duckduckgo-email-protection/\"]");
    }

    /** a (confidence 0.90) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator duckDuckGoSubscribersLink() {
        return page.getByRole(AriaRole.LINK, new Page.GetByRoleOptions().setName("DuckDuckGo subscribers"));
    }

    /** a (confidence 0.92) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator vPNLink() {
        return page.locator("[href=\"https://duckduckgo.com/duckduckgo-help-pages/privacy-pro/vpn/\"]");
    }

    /** a (confidence 0.92) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator duckAiLink3() {
        return page.locator("[href=\"https://duckduckgo.com/duckduckgo-help-pages/duckai\"]");
    }

    /** a (confidence 0.92) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator personalInformationRemovalLink() {
        return page.locator("[href=\"https://duckduckgo.com/duckduckgo-help-pages/privacy-pro/personal-information-removal/\"]");
    }

    /** a (confidence 0.92) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator identityTheftRestorationLink() {
        return page.locator("[href=\"https://duckduckgo.com/duckduckgo-help-pages/privacy-pro/identity-theft-restoration/\"]");
    }

    /** a (confidence 0.37) */
    // signature prefix: div:->div:->main:->div:->main:-
    /** matches 3 — уточните */
    public Locator learnMoreLink2() {
        return page.locator("[href=\"https://duckduckgo.com/duckduckgo-help-pages/company/how-does-duckduckgo-protect-privacy/\"]").first();
    }

    /** button (confidence 0.90) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator doesDuckDuckGoBlockAllButton() {
        return page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Does DuckDuckGo block all trackers on websites I visit?"));
    }

    /** a (confidence 0.90) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator neverTracksYouLink() {
        return page.getByRole(AriaRole.LINK, new Page.GetByRoleOptions().setName("never tracks you"));
    }

    /** a (confidence 0.37) */
    // signature prefix: div:->div:->main:->div:->main:-
    /** matches 4 — уточните */
    public Locator webTrackingProtectionsLink() {
        return page.locator("[href=\"https://duckduckgo.com/duckduckgo-help-pages/privacy/web-tracking-protections/\"]").first();
    }

    /** a (confidence 0.92) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator link3rdPartyTrackerLoading() {
        return page.locator("[href=\"https://duckduckgo.com/duckduckgo-help-pages/privacy/web-tracking-protections/#3rd-party-tracker-loading-protection\"]");
    }

    /** a (confidence 0.92) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator globalPrivacyControlLink() {
        return page.locator("[href=\"https://duckduckgo.com/duckduckgo-help-pages/privacy/web-tracking-protections/#global-privacy-control-gpc\"]");
    }

    /** a (confidence 0.92) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator linkTrackingProtectionLink() {
        return page.locator("[href=\"https://duckduckgo.com/duckduckgo-help-pages/privacy/web-tracking-protections/#link-tracking-protection\"]");
    }

    /** a (confidence 0.92) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator cNAMECloakingProtectionLink() {
        return page.locator("[href=\"https://duckduckgo.com/duckduckgo-help-pages/privacy/web-tracking-protections/#cname-cloaking-protection\"]");
    }

    /** a (confidence 0.92) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator googleAMPProtectionLink() {
        return page.locator("[href=\"https://duckduckgo.com/duckduckgo-help-pages/privacy/web-tracking-protections/#google-amp-protection\"]");
    }

    /** a (confidence 0.90) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator moreLink() {
        return page.getByRole(AriaRole.LINK, new Page.GetByRoleOptions().setName("more"));
    }

    /** a (confidence 0.92) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator listOfTrackersLink() {
        return page.locator("[href=\"https://github.com/duckduckgo/tracker-blocklists\"]");
    }

    /** a (confidence 0.92) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator listOfExceptionsLink() {
        return page.locator("[href=\"https://github.com/duckduckgo/privacy-configuration\"]");
    }

    /** a (confidence 0.92) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator learnMoreLink3() {
        return page.locator("[href=\"https://duckduckgo.com/duckduckgo-help-pages/privacy/web-tracking-protections\"]");
    }

    /** button (confidence 0.90) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator howManyPeopleUseButton() {
        return page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("How many people use DuckDuckGo?"));
    }

    /** a (confidence 0.92) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator holdsThe2PositionLink() {
        return page.locator("[href=\"https://duckduckgo.com/cloudflare-radar-report\"]");
    }

    /** button (confidence 0.90) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator howDoesDuckDuckGoMakeButton() {
        return page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("How does DuckDuckGo make money?"));
    }

    /** a (confidence 0.90) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator privacyPolicyLink() {
        return page.locator("main").getByRole(AriaRole.LINK, new Page.GetByRoleOptions().setName("Privacy Policy"));
    }

    /** a (confidence 0.90) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator duckDuckGoSubscriptionLink() {
        return page.getByRole(AriaRole.LINK, new Page.GetByRoleOptions().setName("DuckDuckGo subscription"));
    }

    /** a (confidence 0.37) */
    // signature prefix: div:->div:->main:->div:->main:-
    /** matches 3 — уточните */
    public Locator learnMoreLink4() {
        return page.locator("[href=\"https://duckduckgo.com/duckduckgo-help-pages/company/how-duckduckgo-makes-money/\"]").first();
    }

    /** button (confidence 0.90) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator whyUseDuckDuckGoInsteadButton() {
        return page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Why use DuckDuckGo instead of Google?"));
    }

    /** a (confidence 0.37) */
    // signature prefix: div:->div:->main:->div:->main:-
    /** matches 3 — уточните */
    public Locator privacyRespectingSearchAdsLink2() {
        return page.locator("[href=\"https://duckduckgo.com/duckduckgo-help-pages/company/how-duckduckgo-makes-money/\"]").first();
    }

    /** a (confidence 0.92) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator youReNotAloneLink() {
        return page.locator("[href=\"https://www.theatlantic.com/ideas/archive/2022/06/google-search-algorithm-internet/661325/\"]");
    }

    /** a (confidence 0.92) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator automaticallyBlockingCookiePopLink() {
        return page.locator("[href=\"https://duckduckgo.com/duckduckgo-help-pages/privacy/web-tracking-protections/#cookie-pop-up-management\"]");
    }

    /** a (confidence 0.37) */
    // signature prefix: div:->div:->main:->div:->main:-
    /** matches 4 — уточните */
    public Locator webTrackingProtectionsLink2() {
        return page.locator("[href=\"https://duckduckgo.com/duckduckgo-help-pages/privacy/web-tracking-protections/\"]").first();
    }

    /** button (confidence 0.90) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator isIncognitoModePrivateButton() {
        return page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Is Incognito Mode private?"));
    }

    /** a (confidence 0.37) */
    // signature prefix: div:->div:->main:->div:->main:-
    /** matches 3 — уточните */
    public Locator learnMoreLink5() {
        return page.locator("[href=\"https://duckduckgo.com/duckduckgo-help-pages/company/how-does-duckduckgo-protect-privacy/\"]").first();
    }

    /** button (confidence 0.90) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator howDoDuckDuckGoSearchButton() {
        return page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("How do DuckDuckGo Search results compare to Google's?"));
    }

    /** a (confidence 0.92) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator bonusFeaturesLink() {
        return page.locator("[href=\"https://duckduckgo.com/bangs\"]");
    }

    /** a (confidence 0.92) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator alwaysImprovingLink() {
        return page.locator("[href=\"https://duckduckgo.com/updates\"]");
    }

    /** a (confidence 0.92) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator learnMoreLink6() {
        return page.locator("[href=\"https://spreadprivacy.com/is-duckduckgo-a-good-search-engine/\"]");
    }

    /** button (confidence 0.90) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator isDuckDuckGoOwnedByButton() {
        return page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Is DuckDuckGo owned by Google or any other entity?"));
    }

    /** a (confidence 0.37) */
    // signature prefix: div:->div:->main:->div:->main:-
    /** matches 3 — уточните */
    public Locator learnMoreLink7() {
        return page.locator("[href=\"https://duckduckgo.com/duckduckgo-help-pages/company/how-does-duckduckgo-protect-privacy/\"]").first();
    }

    /** a (confidence 0.92) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator aboutDuckDuckGoLink() {
        return page.locator("[href=\"/about\"]");
    }

    /** a (confidence 0.92) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator aboutOurBrowserLink() {
        return page.locator("[href=\"/app?origin=funnel_home_website__details\"]");
    }

    /** a (confidence 0.92) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator whatSNewLink() {
        return page.locator("[href=\"/updates\"]");
    }

    /** a (confidence 0.90) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator comparePrivacyLink() {
        return page.getByRole(AriaRole.LINK, new Page.GetByRoleOptions().setName("Compare Privacy"));
    }

    /** a (confidence 0.92) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator blogLink() {
        return page.locator("[href=\"https://spreadprivacy.com\"]");
    }

    /** a (confidence 0.92) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator newsletterLink() {
        return page.locator("[href=\"/newsletter\"]");
    }

    /** a (confidence 0.92) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator podcastLink() {
        return page.locator("[href=\"https://insideduckduckgo.substack.com/?showWelcome=true\"]");
    }

    /** a (confidence 0.92) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator helpLink() {
        return page.locator("[href=\"https://duckduckgo.com/duckduckgo-help-pages\"]");
    }

    /** a (confidence 0.92) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator communityLink() {
        return page.locator("[href=\"https://www.reddit.com/r/duckduckgo/\"]");
    }

    /** a (confidence 0.92) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator careersLink() {
        return page.locator("[href=\"/hiring\"]");
    }

    /** a (confidence 0.92) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator privacyPolicyLink2() {
        return page.locator("[href=\"/privacy\"]");
    }

    /** a (confidence 0.92) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator termsOfServiceLink() {
        return page.locator("[href=\"/terms\"]");
    }

    /** a (confidence 0.92) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator pressKitLink() {
        return page.locator("[href=\"/press\"]");
    }

    /** a (confidence 0.92) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator advertiseOnSearchLink() {
        return page.locator("[href=\"https://duckduckgo.com/duckduckgo-help-pages/company/advertise-on-duckduckgo-search\"]");
    }

    /** a (confidence 0.92) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator collaborationsLink() {
        return page.locator("[href=\"/collaborations\"]");
    }

    /** a (confidence 0.90) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator chooseDuckDuckGoOverChromeLink2() {
        return page.locator("footer").getByRole(AriaRole.LINK, new Page.GetByRoleOptions().setName("choose DuckDuckGo over Chrome and other browsers"));
    }

    /** a (confidence 0.90) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator duckAiLink4() {
        return page.locator("footer").getByRole(AriaRole.LINK, new Page.GetByRoleOptions().setName("Duck.ai"));
    }

    /** a (confidence 0.92) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator privacyRespectingSearchAdsLink3() {
        return page.locator("[href=\"https://duckduckgo.com/duckduckgo-help-pages/company/how-duckduckgo-makes-money\"]");
    }

    /** a (confidence 0.90) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator macLink3() {
        return page.locator("footer").getByRole(AriaRole.LINK, new Page.GetByRoleOptions().setName("Mac"));
    }

    /** a (confidence 0.90) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator windowsLink3() {
        return page.locator("footer").getByRole(AriaRole.LINK, new Page.GetByRoleOptions().setName("Windows"));
    }

    /** a (confidence 0.92) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator iOSLink3() {
        return page.locator("[href=\"https://apps.apple.com/app/duckduckgo-privacy-browser/id663592361?platform=iphone\"]");
    }

    /** a (confidence 0.90) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator androidLink3() {
        return page.locator("footer").getByRole(AriaRole.LINK, new Page.GetByRoleOptions().setName("Android"));
    }

    /** a (confidence 0.92) */
    // signature prefix: div:->div:->main:->div:->main:-
    public Locator duckDuckGoLink() {
        return page.locator("[href=\"https://duckduckgo.com\"]");
    }
}

